AllCops:
  Exclude:
    - 'bin/**/*'
    - 'log/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - '*.gemspec'
    - 'spec/spec_helper.rb'
  TargetRubyVersion: 2.2

Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Alias:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/FileName:
  Exclude:
    - 'lib/gems-cli.rb'

Style/Lambda:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

TrailingBlankLines:
  Enabled: false
